#priority 100

import crafttweaker.item.IItemStack;

global metals as IItemStack[string][string] = {
    // ===== TerraFirmaCraft ===== //
    "bismuth": {
        "ingot":                        <tfc:metal/ingot/bismuth>,
        "double_ingot":                 <tfc:metal/double_ingot/bismuth>,
        "scrap":                        <tfc:metal/scrap/bismuth>,
        "dust":                         <tfc:metal/dust/bismuth>,
        "nugget":                       <tfc:metal/nugget/bismuth>,
        "sheet":                        <tfc:metal/sheet/bismuth>,
        "double_sheet":                 <tfc:metal/double_sheet/bismuth>,
    },
    "bismuth_bronze": {
        "ingot":                        <tfc:metal/ingot/bismuth_bronze>,
        "double_ingot":                 <tfc:metal/double_ingot/bismuth_bronze>,
        "scrap":                        <tfc:metal/scrap/bismuth_bronze>,
        "dust":                         <tfc:metal/dust/bismuth_bronze>,
        "nugget":                       <tfc:metal/nugget/bismuth_bronze>,
        "sheet":                        <tfc:metal/sheet/bismuth_bronze>,
        "double_sheet":                 <tfc:metal/double_sheet/bismuth_bronze>,
    },
    "black_bronze": {
        "ingot":                        <tfc:metal/ingot/black_bronze>,
        "double_ingot":                 <tfc:metal/double_ingot/black_bronze>,
        "scrap":                        <tfc:metal/scrap/black_bronze>,
        "dust":                         <tfc:metal/dust/black_bronze>,
        "nugget":                       <tfc:metal/nugget/black_bronze>,
        "sheet":                        <tfc:metal/sheet/black_bronze>,
        "double_sheet":                 <tfc:metal/double_sheet/black_bronze>,
    },
    "brass": {
        "ingot":                        <tfc:metal/ingot/brass>,
        "double_ingot":                 <tfc:metal/double_ingot/brass>,
        "scrap":                        <tfc:metal/scrap/brass>,
        "dust":                         <tfc:metal/dust/brass>,
        "nugget":                       <tfc:metal/nugget/brass>,
        "sheet":                        <tfc:metal/sheet/brass>,
        "double_sheet":                 <tfc:metal/double_sheet/brass>,
    },
    "bronze": {
        "ingot":                        <tfc:metal/ingot/bronze>,
        "double_ingot":                 <tfc:metal/double_ingot/bronze>,
        "scrap":                        <tfc:metal/scrap/bronze>,
        "dust":                         <tfc:metal/dust/bronze>,
        "nugget":                       <tfc:metal/nugget/bronze>,
        "sheet":                        <tfc:metal/sheet/bronze>,
        "double_sheet":                 <tfc:metal/double_sheet/bronze>,
        "block":                        <thermalfoundation:storage_alloy:3>,
        "gear":                         <thermalfoundation:material:291>,
        "coin":                         <thermalfoundation:coin:99>,
        "plate":                        <thermalfoundation:material:355>,
    },
    "copper": {
        "ingot":                        <tfc:metal/ingot/copper>,
        "double_ingot":                 <tfc:metal/double_ingot/copper>,
        "scrap":                        <tfc:metal/scrap/copper>,
        "dust":                         <tfc:metal/dust/copper>,
        "nugget":                       <tfc:metal/nugget/copper>,
        "sheet":                        <tfc:metal/sheet/copper>,
        "double_sheet":                 <tfc:metal/double_sheet/copper>,
        "block":                        <immersiveengineering:storage:0>,
        "sheetmetal":                   <immersiveengineering:sheetmetal:0>,
        "fence":                        <immersiveposts:fence_copper>,
        "rod":                          <immersiveposts:metal_rods:1>,
        "gear":                         <thermalfoundation:material:256>,
        "coin":                         <thermalfoundation:coin:64>,
        "plate":                        <thermalfoundation:material:320>,
        "wire":                         <immersiveengineering:material:20>,
    },
    "gold": {
        "ingot":                        <tfc:metal/ingot/gold>,
        "double_ingot":                 <tfc:metal/double_ingot/gold>,
        "scrap":                        <tfc:metal/scrap/gold>,
        "dust":                         <tfc:metal/dust/gold>,
        "nugget":                       <tfc:metal/nugget/gold>,
        "sheet":                        <tfc:metal/sheet/gold>,
        "double_sheet":                 <tfc:metal/double_sheet/gold>,
        "block":                        <minecraft:gold_block>,
        "sheetmetal":                   <immersiveengineering:sheetmetal:10>,
        "fence":                        <immersiveposts:fence_gold>,
        "rod":                          <tfc:metal/rod/gold>,
        "gear":                         <thermalfoundation:material:25>,
        "coin":                         <thermalfoundation:coin:1>,
        "plate":                        <thermalfoundation:material:33>,
    },
    "lead": {
        "ingot":                        <tfc:metal/ingot/lead>,
        "double_ingot":                 <tfc:metal/double_ingot/lead>,
        "scrap":                        <tfc:metal/scrap/lead>,
        "dust":                         <tfc:metal/dust/lead>,
        "nugget":                       <tfc:metal/nugget/lead>,
        "sheet":                        <tfc:metal/sheet/lead>,
        "double_sheet":                 <tfc:metal/double_sheet/lead>,
        "block":                        <immersiveengineering:storage:2>,
        "sheetmetal":                   <immersiveengineering:sheetmetal:2>,
        "fence":                        <immersiveposts:fence_lead>,
        "rod":                          <immersiveposts:metal_rods:2>,
        "gear":                         <thermalfoundation:material:259>,
        "coin":                         <thermalfoundation:coin:67>,
        "plate":                        <thermalfoundation:material:323>,
    },
    "nickel": {
        "ingot":                        <tfc:metal/ingot/nickel>,
        "double_ingot":                 <tfc:metal/double_ingot/nickel>,
        "scrap":                        <tfc:metal/scrap/nickel>,
        "dust":                         <tfc:metal/dust/nickel>,
        "nugget":                       <tfc:metal/nugget/nickel>,
        "sheet":                        <tfc:metal/sheet/nickel>,
        "double_sheet":                 <tfc:metal/double_sheet/nickel>,
        "block":                        <immersiveengineering:storage:4>,
        "sheetmetal":                   <immersiveengineering:sheetmetal:4>,
        "fence":                        <immersiveposts:fence_nickel>,
        "rod":                          <immersiveposts:metal_rods:4>,
        "gear":                         <thermalfoundation:material:261>,
        "coin":                         <thermalfoundation:coin:69>,
        "plate":                        <thermalfoundation:material:325>,
    },
    "rose_gold": {
        "ingot":                        <tfc:metal/ingot/rose_gold>,
        "double_ingot":                 <tfc:metal/double_ingot/rose_gold>,
        "scrap":                        <tfc:metal/scrap/rose_gold>,
        "dust":                         <tfc:metal/dust/rose_gold>,
        "nugget":                       <tfc:metal/nugget/rose_gold>,
        "sheet":                        <tfc:metal/sheet/rose_gold>,
        "double_sheet":                 <tfc:metal/double_sheet/rose_gold>,
    },
    "silver": {
        "ingot":                        <tfc:metal/ingot/silver>,
        "double_ingot":                 <tfc:metal/double_ingot/silver>,
        "scrap":                        <tfc:metal/scrap/silver>,
        "dust":                         <tfc:metal/dust/silver>,
        "nugget":                       <tfc:metal/nugget/silver>,
        "sheet":                        <tfc:metal/sheet/silver>,
        "double_sheet":                 <tfc:metal/double_sheet/silver>,
        "block":                        <immersiveengineering:storage:3>,
        "sheetmetal":                   <immersiveengineering:sheetmetal:3>,
        "fence":                        <immersiveposts:fence_silver>,
        "rod":                          <immersiveposts:metal_rods:3>,
        "gear":                         <thermalfoundation:material:258>,
        "coin":                         <thermalfoundation:coin:66>,
        "plate":                        <thermalfoundation:material:322>,
    },
    "tin": {
        "ingot":                        <tfc:metal/ingot/tin>,
        "double_ingot":                 <tfc:metal/double_ingot/tin>,
        "scrap":                        <tfc:metal/scrap/tin>,
        "dust":                         <tfc:metal/dust/tin>,
        "nugget":                       <tfc:metal/nugget/tin>,
        "sheet":                        <tfc:metal/sheet/tin>,
        "double_sheet":                 <tfc:metal/double_sheet/tin>,
        "block":                        <thermalfoundation:storage:1>,
        "gear":                         <thermalfoundation:material:257>,
        "coin":                         <thermalfoundation:coin:65>,
        "plate":                        <thermalfoundation:material:321>,
    },
    "zinc": {
        "ingot":                        <tfc:metal/ingot/zinc>,
        "double_ingot":                 <tfc:metal/double_ingot/zinc>,
        "scrap":                        <tfc:metal/scrap/zinc>,
        "dust":                         <tfc:metal/dust/zinc>,
        "nugget":                       <tfc:metal/nugget/zinc>,
        "sheet":                        <tfc:metal/sheet/zinc>,
        "double_sheet":                 <tfc:metal/double_sheet/zinc>,
    },
    "sterling_silver": {
        "ingot":                        <tfc:metal/ingot/sterling_silver>,
        "double_ingot":                 <tfc:metal/double_ingot/sterling_silver>,
        "scrap":                        <tfc:metal/scrap/sterling_silver>,
        "dust":                         <tfc:metal/dust/sterling_silver>,
        "nugget":                       <tfc:metal/nugget/sterling_silver>,
        "sheet":                        <tfc:metal/sheet/sterling_silver>,
        "double_sheet":                 <tfc:metal/double_sheet/sterling_silver>,
    },
    "wrought_iron": {
        "ingot":                        <tfc:metal/ingot/wrought_iron>,
        "double_ingot":                 <tfc:metal/double_ingot/wrought_iron>,
        "scrap":                        <tfc:metal/scrap/wrought_iron>,
        "dust":                         <tfc:metal/dust/wrought_iron>,
        "nugget":                       <tfc:metal/nugget/wrought_iron>,
        "sheet":                        <tfc:metal/sheet/wrought_iron>,
        "double_sheet":                 <tfc:metal/double_sheet/wrought_iron>,
        "rod":                          <tfc:metal/rod/wrought_iron>,
        "block":                        <minecraft:iron_block>,
        "sheetmetal":                   <immersiveengineering:sheetmetal:9>,
        "fence":                        <immersiveposts:fence_iron>,
        "gear":                         <thermalfoundation:material:24>,
        "coin":                         <thermalfoundation:coin:0>,
        "plate":                        <thermalfoundation:material:32>,
    },
    "pig_iron": {
        "ingot":                        <tfc:metal/ingot/pig_iron>,
        "double_ingot":                 <tfc:metal/double_ingot/pig_iron>,
        "scrap":                        <tfc:metal/scrap/pig_iron>,
        "dust":                         <tfc:metal/dust/pig_iron>,
        "nugget":                       <tfc:metal/nugget/pig_iron>,
        "sheet":                        <tfc:metal/sheet/pig_iron>,
        "double_sheet":                 <tfc:metal/double_sheet/pig_iron>,
    },
    "steel": {
        "ingot":                        <tfc:metal/ingot/steel>,
        "double_ingot":                 <tfc:metal/double_ingot/steel>,
        "scrap":                        <tfc:metal/scrap/steel>,
        "dust":                         <tfc:metal/dust/steel>,
        "nugget":                       <tfc:metal/nugget/steel>,
        "sheet":                        <tfc:metal/sheet/steel>,
        "double_sheet":                 <tfc:metal/double_sheet/steel>,
        "block":                        <immersiveengineering:storage:8>,
        "sheetmetal":                   <immersiveengineering:sheetmetal:8>,
        "fence":                        <immersiveengineering:metal_decoration1:0>,
        "scaffolding":                  <immersiveengineering:metal_decoration1:1>,
        "rod":                          <tfc:metal/rod/steel>,
        "wire":                         <immersiveengineering:material:23>,
        "gear":                         <thermalfoundation:material:288>,
        "coin":                         <thermalfoundation:coin:96>,
        "plate":                        <thermalfoundation:material:352>,
    },
    "platinum": {
        "ingot":                        <tfc:metal/ingot/platinum>,
        "double_ingot":                 <tfc:metal/double_ingot/platinum>,
        "scrap":                        <tfc:metal/scrap/platinum>,
        "dust":                         <tfc:metal/dust/platinum>,
        "nugget":                       <tfc:metal/nugget/platinum>,
        "sheet":                        <tfc:metal/sheet/platinum>,
        "double_sheet":                 <tfc:metal/double_sheet/platinum>,
        "block":                        <thermalfoundation:storage:6>,
        "gear":                         <thermalfoundation:material:262>,
        "coin":                         <thermalfoundation:coin:70>,
        "plate":                        <thermalfoundation:material:326>,
    },
    "black_steel": {
        "ingot":                        <tfc:metal/ingot/black_steel>,
        "double_ingot":                 <tfc:metal/double_ingot/black_steel>,
        "scrap":                        <tfc:metal/scrap/black_steel>,
        "dust":                         <tfc:metal/dust/black_steel>,
        "nugget":                       <tfc:metal/nugget/black_steel>,
        "sheet":                        <tfc:metal/sheet/black_steel>,
        "double_sheet":                 <tfc:metal/double_sheet/black_steel>,
    },
    "blue_steel": {
        "ingot":                        <tfc:metal/ingot/blue_steel>,
        "double_ingot":                 <tfc:metal/double_ingot/blue_steel>,
        "scrap":                        <tfc:metal/scrap/blue_steel>,
        "dust":                         <tfc:metal/dust/blue_steel>,
        "nugget":                       <tfc:metal/nugget/blue_steel>,
        "sheet":                        <tfc:metal/sheet/blue_steel>,
        "double_sheet":                 <tfc:metal/double_sheet/blue_steel>,
    },
    "red_steel": {
        "ingot":                        <tfc:metal/ingot/red_steel>,
        "double_ingot":                 <tfc:metal/double_ingot/red_steel>,
        "scrap":                        <tfc:metal/scrap/red_steel>,
        "dust":                         <tfc:metal/dust/red_steel>,
        "nugget":                       <tfc:metal/nugget/red_steel>,
        "sheet":                        <tfc:metal/sheet/red_steel>,
        "double_sheet":                 <tfc:metal/double_sheet/red_steel>,
    },
    "weak_steel": {
        "ingot":                        <tfc:metal/ingot/weak_steel>
    },
    "weak_blue_steel": {
        "ingot":                        <tfc:metal/ingot/weak_blue_steel>
    },
    "weak_red_steel": {
        "ingot":                        <tfc:metal/ingot/weak_red_steel>
    },
    "high_carbon_steel": {
        "ingot":                        <tfc:metal/ingot/high_carbon_steel>
    },
    "high_carbon_blue_steel": {
        "ingot":                        <tfc:metal/ingot/high_carbon_blue_steel>
    },
    "high_carbon_red_steel": {
        "ingot":                        <tfc:metal/ingot/high_carbon_red_steel>
    },
    "high_carbon_black_steel": {
        "ingot":                        <tfc:metal/ingot/high_carbon_black_steel>
    },
    "unknown": {
        "ingot":                        <tfc:metal/ingot/unknown>
    },
    // ===== Thermal Foundation ===== //
    "iridium": {
        "ingot":                        <thermalfoundation:material:135>,
        "dust":                         <thermalfoundation:material:71>,
        "nugget":                       <thermalfoundation:material:199>,
        "block":                        <thermalfoundation:storage:7>,
        "gear":                         <thermalfoundation:material:263>,
        "coin":                         <thermalfoundation:coin:71>,
        "plate":                        <thermalfoundation:material:327>,
    },
    "signalum": {
        "ingot":                        <thermalfoundation:material:165>,
        "dust":                         <thermalfoundation:material:101>,
        "nugget":                       <thermalfoundation:material:229>,
        "block":                        <thermalfoundation:storage_alloy:5>,
        "gear":                         <thermalfoundation:material:293>,
        "coin":                         <thermalfoundation:coin:101>,
        "plate":                        <thermalfoundation:material:357>,
    },
    "lumium": {
        "ingot":                        <thermalfoundation:material:166>,
        "dust":                         <thermalfoundation:material:102>,
        "nugget":                       <thermalfoundation:material:230>,
        "block":                        <thermalfoundation:storage_alloy:6>,
        "gear":                         <thermalfoundation:material:294>,
        "coin":                         <thermalfoundation:coin:102>,
        "plate":                        <thermalfoundation:material:358>,
    },
    "enderium": {
        "ingot":                        <thermalfoundation:material:167>,
        "dust":                         <thermalfoundation:material:103>,
        "nugget":                       <thermalfoundation:material:231>,
        "gear":                         <thermalfoundation:material:295>,
        "coin":                         <thermalfoundation:coin:103>,
        "plate":                        <thermalfoundation:material:359>,
        "block":                        <thermalfoundation:storage_alloy:7>,
    },
    "aluminum": {
        "ingot":                        <thermalfoundation:material:132>,
        "dust":                         <thermalfoundation:material:68>,
        "nugget":                       <thermalfoundation:material:196>,
        "gear":                         <thermalfoundation:material:260>,
        "coin":                         <thermalfoundation:coin:68>,
        "plate":                        <thermalfoundation:material:324>,
        "block":                        <immersiveengineering:storage:1>,
        "sheetmetal":                   <immersiveengineering:sheetmetal:1>,
        "fence":                        <immersiveengineering:metal_decoration1:4>,
        "scaffolding":                  <immersiveengineering:metal_decoration1:5>,
        "rod":                          <immersiveengineering:material:3>,
        "wire":                         <immersiveengineering:material:22>,
    },
    "mithril": {
        "ingot":                        <thermalfoundation:material:136>,
        "dust":                         <thermalfoundation:material:72>,
        "nugget":                       <thermalfoundation:material:200>,
        "block":                        <thermalfoundation:storage:8>,
        "gear":                         <thermalfoundation:material:264>,
        "coin":                         <thermalfoundation:coin:72>,
        "plate":                        <thermalfoundation:material:328>,
    },
    "electrum": {
        "ingot":                        <thermalfoundation:material:161>,
        "dust":                         <thermalfoundation:material:97>,
        "nugget":                       <thermalfoundation:material:225>,
        "block":                        <immersiveengineering:storage:7>,
        "gear":                         <thermalfoundation:material:289>,
        "coin":                         <thermalfoundation:coin:97>,
        "plate":                        <thermalfoundation:material:353>,
        "sheetmetal":                   <immersiveengineering:sheetmetal:7>,
        "wire":                         <immersiveengineering:material:21>,
        "fence":                        <immersiveposts:fence_electrum>,
        "rod":                          <immersiveposts:metal_rods:6>,
    },
    "invar": {
        "ingot":                        <thermalfoundation:material:162>,
        "dust":                         <thermalfoundation:material:98>,
        "nugget":                       <thermalfoundation:material:226>,
        "gear":                         <thermalfoundation:material:290>,
        "plate":                        <thermalfoundation:material:354>,
        "block":                        <thermalfoundation:storage_alloy:2>,
        "coin":                         <thermalfoundation:coin:98>,
    },
    "constantan": {
        "ingot":                        <thermalfoundation:material:164>,
        "dust":                         <thermalfoundation:material:100>,
        "nugget":                       <thermalfoundation:material:228>,
        "gear":                         <thermalfoundation:material:292>,
        "plate":                        <thermalfoundation:material:356>,
        "block":                        <immersiveengineering:storage:6>,
        "sheetmetal":                   <immersiveengineering:sheetmetal:6>,
        "fence":                        <immersiveposts:fence_constantan>,
        "rod":                          <immersiveposts:metal_rods:5>,
        "coin":                         <thermalfoundation:coin:100>,
    },
    // ===== Tinkers' Construct ===== //
    "cobalt": {
        "ingot":                        <tconstruct:ingots:0>,
        "dust":                         <exnihilocreatio:item_ore_cobalt:2>,
        "nugget":                       <tconstruct:nuggets:0>,
        "block":                        <tconstruct:metal:0>,
    },
    "ardite": {
        "ingot":                        <tconstruct:ingots:1>,
        "dust":                         <exnihilocreatio:item_ore_ardite:2>,
        "nugget":                       <tconstruct:nuggets:1>,
        "block":                        <tconstruct:metal:1>,
    },
    "manyullyn": {
        "ingot":                        <tconstruct:ingots:2>,
        "nugget":                       <tconstruct:nuggets:2>,
        "block":                        <tconstruct:metal:2>,
    },
    "knightslime": {
        "ingot":                        <tconstruct:ingots:3>,
        "nugget":                       <tconstruct:nuggets:3>,
        "block":                        <tconstruct:metal:3>,
    },
    "pigiron": {
        "ingot":                        <tconstruct:ingots:4>,
        "nugget":                       <tconstruct:nuggets:4>,
        "block":                        <tconstruct:metal:4>,
    },
    "alubrass": {
        "ingot":                        <tconstruct:ingots:5>,
        "nugget":                       <tconstruct:nuggets:5>,
        "block":                        <tconstruct:metal:5>,
    },
    // ===== Immersive Engineering ===== //
    "hop_graphite": {
        "ingot":                        <immersiveengineering:material:19>,
        "dust":                         <immersiveengineering:material:18>,
    },
    "uranium": {
        "ingot":                        <immersiveengineering:metal:5>,
        "dust":                         <immersiveengineering:metal:14>,
        "nugget":                       <immersiveengineering:metal:25>,
        "plate":                        <immersiveengineering:metal:35>,
        "block":                        <immersiveengineering:storage:5>,
        "sheetmetal":                   <immersiveengineering:sheetmetal:5>,
        "rod":                          <immersiveposts:metal_rods:7>,
        "fence":                        <immersiveposts:fence_uranium>,
    },
    // ===== Project Red ===== //
    "red_alloy": {
        "ingot":                        <projectred-core:resource_item:103>,
    },
    "electrotine": {
        "ingot":                        <projectred-core:resource_item:104>,
        "dust":                         <projectred-core:resource_item:105>,
    },
    // ===== Soul Shards ===== //
    "corrupted": {
        "ingot":                        <soulshardstow:materials:0>
    },
};

global metalMeltingHeats as int[string] = {
    "bismuth":                       270,
    "bismuth_bronze":                985,
    "black_bronze":                 1070,
    "brass":                         930,
    "bronze":                        950,
    "copper":                       1080,
    "gold":                         1060,
    "lead":                          328,
    "nickel":                       1453,
    "rose_gold":                     960,
    "silver":                        961,
    "tin":                           230,
    "zinc":                          420,
    "sterling_silver":               900,
    "wrought_iron":                 1535,
    "pig_iron":                     1535,
    "steel":                        1540,
    "platinum":                     1730,
    "black_steel":                  1485,
    "blue_steel":                   1540,
    "red_steel":                    1540,
    "weak_steel":                   1540,
    "weak_blue_steel":              1540,
    "weak_red_steel":               1540,
    "high_carbon_steel":            1540,
    "high_carbon_blue_steel":       1540,
    "high_carbon_red_steel":        1540,
    "high_carbon_black_steel":      1540,
    "unknown":                      1250,
    "iridium":                      1100,
    "signalum":                      780,
    "lumium":                        460,
    "enderium":                     1910,
    "aluminum":                      660,
    "mithril":                       270,
    "electrum":                     1769,
    "invar":                        1690,
    "constantan":                   1220,
    "cobalt":                       1495,
    "ardite":                       1495,
    "manyullyn":                    1765,
    "knightslime":                   140,
    "pigiron":                       100,
    "alubrass":                      900,
    "hop_graphite":                 3600,
    "uranium":                      1132,
    "red_alloy":                     480,
    "electrotine":                   960,
    "corrupted":                     666,
};

global metalSpecificHeats as float[string] = {
    "bismuth":                      0.14,
    "bismuth_bronze":               0.35,
    "black_bronze":                 0.35,
    "brass":                        0.35,
    "bronze":                       0.35,
    "copper":                       0.35,
    "gold":                         0.60,
    "lead":                         0.22,
    "nickel":                       0.48,
    "rose_gold":                    0.35,
    "silver":                       0.48,
    "tin":                          0.14,
    "zinc":                         0.21,
    "sterling_silver":              0.35,
    "wrought_iron":                 0.35,
    "pig_iron":                     0.35,
    "steel":                        0.35,
    "platinum":                     0.35,
    "black_steel":                  0.35,
    "blue_steel":                   0.35,
    "red_steel":                    0.35,
    "weak_steel":                   0.35,
    "weak_blue_steel":              0.35,
    "weak_red_steel":               0.35,
    "high_carbon_steel":            0.35,
    "high_carbon_blue_steel":       0.35,
    "high_carbon_red_steel":        0.35,
    "high_carbon_black_steel":      0.35,
    "unknown":                      0.50,
    "iridium":                      0.35,
    "signalum":                     0.50,
    "lumium":                       0.10,
    "enderium":                     0.80,
    "aluminum":                     0.40,
    "mithril":                      0.15,
    "electrum":                     0.20,
    "invar":                        0.40,
    "constantan":                   0.25,
    "cobalt":                       0.40,
    "ardite":                       0.40,
    "manyullyn":                    0.40,
    "knightslime":                  0.10,
    "pigiron":                      0.10,
    "alubrass":                     0.15,
    "hop_graphite":                 0.50,
    "uranium":                      0.40,
    "red_alloy":                    0.20,
    "electrotine":                  0.20,
    "corrupted":                    0.15,
};

for name, metal in metals {
    for variety, metalItem in metal {
        metalItem.addTooltip("§e[CT] METAL: " ~ name);
        metalItem.addTooltip("§e[CT] VARIETY: " ~ variety);

        if(!isNull(metalMeltingHeats[name])) {
            metalItem.addTooltip("§e[CT] MELT: " ~ (metalMeltingHeats[name] as string) ~ "°C");
        } else {
            metalItem.addTooltip("§e[CT] MELT: §cN/A");
        }

        if(!isNull(metalSpecificHeats[name])) {
            metalItem.addTooltip("§e[CT] HEAT CAP.: " ~ (metalSpecificHeats[name] as string));
        } else {
            metalItem.addTooltip("§e[CT] HEAT CAP.: §cN/A");
        }
    }
}